version: '3'

services:
  basket_team:
    build:
      context: .
      dockerfile: openjdk.Dockerfile
    container_name: 'basket_team'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.basket_team.rule=Host(`api.basket-team.q91711ta.beget.tech`)"
      - "traefik.http.routers.basket_team.entrypoints=web"
      - "traefik.http.middlewares.basket_team.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST"
      - "traefik.http.middlewares.basket_team.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.basket_team.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.basket_team.headers.addvaryheader=true"
    ports:
      - "8081"
    networks:
      - webserver

networks:
  webserver:
    driver: bridge
    external: true


