version: '3'

services:
  basket_team:
    build:
      context: .
      dockerfile: openjdk.Dockerfile
    container_name: 'basket_team'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.basket_team.rule=Host(`api.basket-team.q91711ta.beget.tech`)"
      - "traefik.http.routers.basket_team.entrypoints=web"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://api.basket-team.q91711ta.beget.tech"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"
    ports:
      - "8081"
    networks:
      - webserver

networks:
  webserver:
    driver: bridge
    external: true


