version: '3'

services:
  basket_team:
    build:
      context: .
      dockerfile: openjdk.Dockerfile
    container_name: 'basket_team'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.basket_team.rule=Host(`api.basket-team.q91711ta.beget.tech`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=myresolver"
    ports:
      - "8081"
    networks:
      - webserver

networks:
  webserver:
    driver: bridge
    external: true


